version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: techdemobackend/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:Kru%4019@technical_demo-db-1:5435/resource_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: techdemofinal/Dockerfile
    ports:
      - "3003:80"
    environment:
      - VITE_BACKEND_URL=http://backend:8002
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: resource_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kru@19
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
