version: "3.8"

services:
  backend:
    build:
      context: ./techdemobackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL} # Use secret file instead of env variable
     # Attach the secret to this service
    networks:
      - app-network
    
  frontend:
    build:
      context: ./techdemofinal
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network
    deploy:
      replicas: 1
secrets:
  database_url_secret:
    external: true  # Docker will look for the secret created in step 1

networks:
  app-network:
    driver: bridge
