adminPassword: resource
persistence:
  enabled: true
  existingClaim: grafana-pvc  # Attach the PVC created earlier
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: managed-csi  # Matches the PVC's storage class

service:
  type: LoadBalancer
