global:
  resolve_timeout: 5m

route:
  receiver: "slack"
  group_by: ["alertname", "severity"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers:
        - alertname="Watchdog"
      receiver: "null"

receivers:
  - name: "null"

  - name: "slack"
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        channel: "#alerts"
        send_resolved: true
        title: "*[{{ .Status }}]* {{ .CommonLabels.alertname }}"
        text: "{{ .CommonAnnotations.summary }}\n{{ .CommonAnnotations.description }}"

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity=~"warning|info"
    equal:
      - namespace
      - alertname

  - source_matchers:
      - severity="warning"
    target_matchers:
      - severity="info"
    equal:
      - namespace
      - alertname

  - source_matchers:
      - alertname="InfoInhibitor"
    target_matchers:
      - severity="info"
    equal:
      - namespace

  - target_matchers:
      - alertname="InfoInhibitor"

templates:
  - /etc/alertmanager/config/*.tmpl

alertmanager:
  extraArgs:
    cluster.listen-address: "0.0.0.0:9094"
