

global:
  environment: production

backend:
  name: resource-monitor-backen
  image:
    repository: krupaht/lastsh
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  port: 8080
  service:
    type: LoadBalancer  
    port: 8080
  hpa:
    enabled: false
    minReplicas: 2
    maxReplicas: 2
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  env:
    NODE_ENV: production
    DB_HOST: resourcepostgres.postgres.database.azure.com
    DB_NAME: resource_db
    DB_PORT: "5432"


frontend:
  name: resource-monitor-frontend
  image:
    repository: krupaht/firstsh
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  port: 80
  service:
    type: LoadBalancer 
    port: 80
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
  env:
    VITE_BACKEND_URL: "http://51.8.199.133:8080"  
serviceAccount:
  create: false  

ingress:
  enabled: false  

database:
  existingSecret: db-credentials 
  sslMode: require
dbCredentials:
  create: false


prometheus:
  enabled: true
