apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  host: {{ .Values.database.host | quote }}
  port: {{ .Values.database.port | quote }}
  dbname: {{ .Values.database.name | quote }}
  username: {{ required "Database username is required" .Values.database.username | quote }}
  password: {{ required "Database password is required" .Values.database.password | quote }}
  sslmode: {{ .Values.database.sslMode | quote }}