apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-app-metrics
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: resource-monitor-backend
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
